FROM node:10.15.0-jessie
WORKDIR /api_gateway_service

ARG FRONTEND_HOST_NAME
ARG FRONTEND_HOST_PROTOCOL
ARG SECRET_STRING

ENV FRONTEND_HOST_NAME=$FRONTEND_HOST_NAME
ENV FRONTEND_HOST_PROTOCOL=$FRONTEND_HOST_PROTOCOL
ENV SECRET_STRING=$SECRET_STRING


COPY . .
RUN npm install
# ADD AWS CREDENTIALS FILE


EXPOSE 4000
CMD [ "npm", "run", "docker:prod"]